name: 自动部署文档
on:
  push:
    branches: [ main ]  # 监听 main 分支的推送
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: 构建并部署
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}